version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: 'npm run dev'
    volumes:
      - ./src:/usr/app/src
    ports:
      - 3000:3000
    depends_on:
     - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=proxima
      - POSTGRES_PASSWORD=proxima
      - POSTGRES_DB=proxima
      - SLACK_CLIENT_ID
      - SLACK_CLIENT_SECRET
  postgres:
    image: postgres:13.1-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=proxima
      - POSTGRES_PASSWORD=proxima
      - POSTGRES_DB=proxima
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U proxima -d proxima"]
      interval: 10s
      timeout: 5s
      retries: 5
