swagger: '2.0'
info:
  description: 'Endpoints for Proxima, next-gen interviewing system.'
  version: '1.0.0'
  title: 'Proxima'
  license:
    name: 'Apache 2.0'
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'localhost:3000'
basePath: '/api/v1'
schemes:
  - 'http'
paths:
